### ISSUE TITLE
Proposal to improve alerts

### ISSUE THREAD

**Issue by JonasPf** [terra-money/oracle-feeder#35]
Oracle Price Server can send alerts to Slack and Sentry.io. The alerts look like this: `Kraken is no response!`. Our ops team is getting a lot of different alerts and it is important for them to understand where an alert is coming from.

To be able to better understand the alert I suggest to:

1. Prefix it with `Terra Oracle Price Server`.
2. Add an optional identification string to the config that will be send with the alert. This is important for people that run multiple price servers (e.g. in a HA scenario).

Example: `Terra Oracle Price Server [instance-12345]: Kraken did not respond!`

Furthermore it would be great to support more than just Slack. For example we use Atlassian OpsGenie as our alerting system. I know there are libraries that abstract away the differences between alerting systems. For example: https://github.com/containrrr/shoutrrr or https://github.com/caronc/apprise. I unfortunately do not know if similar libraries exist in the Javascript ecosystem.

**Comment by hanjukim** [comment]
Thanks for the suggestion. Since there's no one has experience with OpsGenie. We would appreciate PR for this.

**Comment by JonasPf** [comment]
Apologies for the delay. It's been a bit busy on my side. It's on my todo list to create a PR but I can't make any promises regarding timelines.

**Comment by terorie** [comment]
@JonasPf Great idea, I'll work on this.
