### ISSUE TITLE
Index.ts vote: error: Unrecognized arguments: --gas-prices 169.77ukrw.

### ISSUE THREAD

**Issue by Tomas-Eminger** [terra-money/oracle-feeder#51]
When upgraded to version 1.4.6 the default start scripts show errors with unrecognized arguments. Has it been removed?

**Comment by lawrencehui** [comment]
Hi there got the same error too and if I try to remove the extra arguments, the script will run but showing:

`timestamp: Fri, 03 Sep 2021 12:21:20 GMT `
`getPrices: source: http://localhost:8532/latest `
`aggregate error`

Any fix that can be done on this?

**Comment by kobrien** [comment]
Also seeing this error, going to revert back to 1.4.5 until there is a fix

**Comment by YunSuk-Yeo** [comment]
Now oracle messages don't need to pay gas fee, so please remove `--gas-prices ~~` flag from your option

**Comment by YunSuk-Yeo** [comment]
> Hi there got the same error too and if I try to remove the extra arguments, the script will run but showing:
> 
> `timestamp: Fri, 03 Sep 2021 12:21:20 GMT `
> `getPrices: source: http://localhost:8532/latest `
> `aggregate error`
> 
> Any fix that can be done on this?

You need to run price server first

**Comment by kobrien** [comment]
ok thank you, will remove --gas-prices, also do you know if `--lcd` is still a required arg?
