### ISSUE TITLE
New API Providers

### ISSUE THREAD

**Issue by gaia** [terra-money/oracle-feeder#56]
With the goal of enhancing resilience and further decentralizing the sources for currency conversion rates, we did some digging and found what are maybe new providers on the block. They are:

https://fer.ee (free, seems properly done)
https://currencyapi.net (paid, doesn't seem to be just another reseller for the same source data as the others)
https://www.frankfurter.app (free, not sure how reliable it is)

and here is a wrapper for some of the already used sources, which also wraps to call fer.ee:
https://github.com/CMiksche/exchangerates-wrapper

**Comment by YunSuk-Yeo** [comment]
Thanks for digging.
We will consider to adding more sources.

**Comment by emidev98** [comment]
Hey @gaia, thanks for the recommendation Fer and Frankfurter will be integrated very soon! We're looking for more of your contributions!
